# Generated by Django 4.2.6 on 2023-10-27 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.CharField(max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('rejected', 'Запись отклонена'), ('accepted', 'Запись опубликована'), ('new', 'Новая запись'), ('pending', 'Проводится модерация')], default='new', max_length=8)),
                ('person_add', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_add', to='tourism_app.tourist')),
            ],
        ),
        migrations.CreateModel(
            name='MountainLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer', models.CharField(choices=[('D', 'Невыносимое испытание'), (None, 'Выберите сложность'), ('C', 'Лучше идти группой'), ('A', 'Приятная прогулка'), ('B', 'Теплая одеждка будет кстате')], max_length=2)),
                ('autumn', models.CharField(choices=[('D', 'Невыносимое испытание'), (None, 'Выберите сложность'), ('C', 'Лучше идти группой'), ('A', 'Приятная прогулка'), ('B', 'Теплая одеждка будет кстате')], max_length=2)),
                ('spring', models.CharField(choices=[('D', 'Невыносимое испытание'), (None, 'Выберите сложность'), ('C', 'Лучше идти группой'), ('A', 'Приятная прогулка'), ('B', 'Теплая одеждка будет кстате')], max_length=2)),
                ('winter', models.CharField(choices=[('D', 'Невыносимое испытание'), (None, 'Выберите сложность'), ('C', 'Лучше идти группой'), ('A', 'Приятная прогулка'), ('B', 'Теплая одеждка будет кстате')], max_length=2)),
                ('mountain_pass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourism_app.mountainpass')),
            ],
        ),
        migrations.CreateModel(
            name='MountainCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('height', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('mountain_pass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourism_app.mountainpass')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('mountain_pass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourism_app.mountainpass')),
            ],
        ),
    ]
