# Generated by Django 4.2.6 on 2023-10-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainlevel',
            name='autumn',
            field=models.CharField(choices=[('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), (None, 'Выберите сложность')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='spring',
            field=models.CharField(choices=[('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), (None, 'Выберите сложность')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='summer',
            field=models.CharField(choices=[('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), (None, 'Выберите сложность')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='winter',
            field=models.CharField(choices=[('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), (None, 'Выберите сложность')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='status',
            field=models.CharField(choices=[('pending', 'Проводится модерация'), ('accepted', 'Запись опубликована'), ('new', 'Новая запись'), ('rejected', 'Запись отклонена')], default='new', max_length=8),
        ),
    ]
