# Generated by Django 4.2.6 on 2023-10-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainlevel',
            name='autumn',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), (None, 'Выберите сложность'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='spring',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), (None, 'Выберите сложность'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='summer',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), (None, 'Выберите сложность'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='winter',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), (None, 'Выберите сложность'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='status',
            field=models.CharField(choices=[('rejected', 'Запись отклонена'), ('new', 'Новая запись'), ('accepted', 'Запись опубликована'), ('pending', 'Проводится модерация')], default='new', max_length=8),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
