# Generated by Django 4.2.6 on 2023-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountainpass',
            name='status',
            field=models.CharField(choices=[('new', 'Новая запись'), ('rejected', 'Запись отклонена'), ('accepted', 'Запись опубликована'), ('pending', 'Проводится модерация')], default='new', max_length=8),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='autumn',
            field=models.CharField(choices=[('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='spring',
            field=models.CharField(choices=[('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='summer',
            field=models.CharField(choices=[('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='winter',
            field=models.CharField(choices=[('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание'), ('A', 'Приятная прогулка'), ('C', 'Лучше идти группой')], max_length=2),
        ),
    ]
