# Generated by Django 4.2.6 on 2023-10-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0002_mountainpass_status_alter_mountainlevel_autumn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='mountain_image',
            new_name='mountain_pass',
        ),
        migrations.RenameField(
            model_name='mountainlevel',
            old_name='hard_level',
            new_name='mountain_pass',
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='autumn',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='spring',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='summer',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='winter',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('C', 'Лучше идти группой'), ('B', 'Теплая одеждка будет кстате'), ('D', 'Невыносимое испытание')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='status',
            field=models.CharField(choices=[('new', 'Новая запись'), ('pending', 'Проводится модерация'), ('accepted', 'Запись опубликована'), ('rejected', 'Запись отклонена')], default='new', max_length=8),
        ),
    ]
