# Generated by Django 4.2.6 on 2023-10-27 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0003_rename_mountain_image_image_mountain_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountaincoords',
            name='height',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='autumn',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('D', 'Невыносимое испытание'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='spring',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('D', 'Невыносимое испытание'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='summer',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('D', 'Невыносимое испытание'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainlevel',
            name='winter',
            field=models.CharField(choices=[('A', 'Приятная прогулка'), ('D', 'Невыносимое испытание'), ('B', 'Теплая одеждка будет кстате'), ('C', 'Лучше идти группой')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mountainpass',
            name='status',
            field=models.CharField(choices=[('pending', 'Проводится модерация'), ('accepted', 'Запись опубликована'), ('rejected', 'Запись отклонена'), (None, 'fffffff'), ('new', 'Новая запись')], default='new', max_length=8),
        ),
    ]
